package com.arun.exception;

import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.experimental.FieldDefaults;

@Getter
@AllArgsConstructor
@FieldDefaults(level = AccessLevel.PRIVATE)
public enum ExceptionCode {

	OK(200),
	CREATED(201),
	
	ACCEPTED(202),
	ALREADY_EXISTS(208),
	
	DELETED(301),
	FOUND(302),
	NOT_MODIFIED(304),
	
	BAD_REQUEST(400),
	VALIDATION_FAILED(400),
	UNAUTHORIZED(401),
	ACCOUNT_IS_DELETED(401),
	USERNAME_OR_PASSWORD_IS_NOT_VALID(403),
	NOT_FOUND(404),
	ARGUMENT_TYPE_MISMATCH(405),
	METHOD_NOT_ALLOWED(405),
	NOT_ACCEPTABLE(406),
	EXPIRED(409),
	NOT_PROCESSED_FORWARD_BECAUSE_SOME_EXCEPTION_IS_OCCUR(409),
	PAYLOAD_TOO_LARGE(413),
	UNSUPPORTED_MEDIA_TYPE(415),
	INVALID_FORMAT_EXCEPTION(422),
	MESSAGE_NOT_READABLE_EXCEPTION(422),
	
	INTERNAL_SERVER_ERROR(500),
	NOT_IMPLEMENTED(501),
	SERVICE_UNAVAILABLE(503),
	INSUFFICIENT_STORAGE(507);
	
	Integer code;
}
